export interface Song {
    "id": string,
    "title": string,
    "danceability": number,
    "energy": number,
    "key": number,
    "loudness": number,
    "mode": number,
    "acousticness": number,
    "instrumentalness": number,
    "liveness": number,
    "valence": number,
    "tempo": number,
    "duration_ms": number,
    "time_signature": number,
    "num_bars": number,
    "num_sections": number,
    "num_segments": number,
    "class": number,
    "rating"?: number,
}